name: Actions Workflow

on: ["push"]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
          git status
          git log --oneline --decorate --graph
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@ad41a6c27317e688719c813b0d6a25685a9bce54
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Log node version
        run: node -v
      - name: Change Node Version
        uses: actions/setup-node@v2
        with: 
          node-version: 14
      - name: Log node version
        run: node -v